FROM ubuntu:xenial

RUN apt update
RUN apt upgrade -y

RUN apt install -y gcc debhelper\
        cdbs\
        lintian\
        build-essential\
        fakeroot \
        devscripts\
        pbuilder \
        dh-make\
        debootstrap\ 
        python-pip\
        wget

RUN mkdir /code/
WORKDIR /code/

ENTRYPOINT ["/bin/bash"]
